# Generated by Django 4.1.1 on 2022-09-28 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('licenca', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.TextField()),
                ('model', models.TextField()),
                ('year', models.IntegerField()),
                ('vin', models.TextField()),
                ('motorista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carro.motorista')),
            ],
        ),
    ]
